// sample-react/src/components/CDPSection.tsx
import React, { useState } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from './ui/card';
import { Button } from './ui/button';
import { Badge } from './ui/badge';
import { Progress } from './ui/progress';
import { AlertTriangle, Plus, Minus, TrendingDown, TrendingUp } from 'lucide-react';
import { Alert, AlertDescription } from './ui/alert';

const cdpPositions = [
  {
    id: 'CDP-001',
    collaterals: [
      { asset: 'ETH', amount: '5.0', value: '$12,500', price: '$2,485.67', change24h: '+3.24', isPositive: true, logo: '⟠' },
      { asset: 'WBTC', amount: '0.15', value: '$6,750', price: '$67,234.12', change24h: '-1.85', isPositive: false, logo: '₿' }
    ],
    loans: [
      { asset: 'USDC', borrowed: '8,500', interestRate: '5.25', price: '$1.00', change24h: '+0.02', isPositive: true, logo: '💰' },
      { asset: 'DAI', borrowed: '2,000', interestRate: '4.85', price: '$0.998', change24h: '-0.12', isPositive: false, logo: '🪙' }
    ],
    healthRatio: 2.1,
    totalCollateral: '$19,250',
    totalDebt: '$10,500',
    liquidationPrice: '$1,890',
    status: 'healthy'
  },
  {
    id: 'CDP-002',
    collaterals: [
      { asset: 'LINK', amount: '1,200', value: '$18,000', price: '$15.00', change24h: '+2.15', isPositive: true, logo: '🔗' }
    ],
    loans: [
      { asset: 'USDT', borrowed: '12,000', interestRate: '6.15', price: '$1.001', change24h: '+0.08', isPositive: true, logo: '💵' }
    ],
    healthRatio: 1.45,
    totalCollateral: '$18,000',
    totalDebt: '$12,000',
    liquidationPrice: '$12.50',
    status: 'warning'
  },
  {
    id: 'CDP-003',
    collaterals: [
      { asset: 'MATIC', amount: '15,000', value: '$13,500', price: '$0.90', change24h: '-4.25', isPositive: false, logo: '🔷' }
    ],
    loans: [
      { asset: 'DAI', borrowed: '7,200', interestRate: '4.95', price: '$0.998', change24h: '-0.12', isPositive: false, logo: '🪙' }
    ],
    healthRatio: 1.85,
    totalCollateral: '$13,500',
    totalDebt: '$7,200',
    liquidationPrice: '$0.65',
    status: 'healthy'
  }
];

// Available assets for collateral
const availableCollaterals = [
  {
    id: 'col1',
    asset: 'ETH',
    price: '$2,485.67',
    change24h: '+3.24',
    isPositive: true,
    ltv: '75%',
    totalSupplied: '$45.2M',
    logo: '⟠'
  },
  {
    id: 'col2',
    asset: 'WBTC',
    price: '$67,234.12',
    change24h: '-1.85',
    isPositive: false,
    ltv: '70%',
    totalSupplied: '$28.7M',
    logo: '₿'
  },
  {
    id: 'col3',
    asset: 'LINK',
    price: '$15.00',
    change24h: '+2.15',
    isPositive: true,
    ltv: '65%',
    totalSupplied: '$12.3M',
    logo: '🔗'
  },
  {
    id: 'col4',
    asset: 'MATIC',
    price: '$0.90',
    change24h: '-4.25',
    isPositive: false,
    ltv: '60%',
    totalSupplied: '$8.9M',
    logo: '🔷'
  }
];

// Available assets for borrowing
const availableLoanResources = [
  {
    id: 'loan1',
    asset: 'USDC',
    price: '$1.00',
    change24h: '+0.02',
    isPositive: true,
    borrowApr: '5.25%',
    availableLiquidity: '$2.5M',
    logo: '💰'
  },
  {
    id: 'loan2',
    asset: 'USDT', 
    price: '$1.001',
    change24h: '+0.08',
    isPositive: true,
    borrowApr: '6.15%',
    availableLiquidity: '$1.8M',
    logo: '💵'
  },
  {
    id: 'loan3',
    asset: 'DAI',
    price: '$0.998',
    change24h: '-0.12',
    isPositive: false,
    borrowApr: '4.85%',
    availableLiquidity: '$3.2M',
    logo: '🪙'
  },
  {
    id: 'loan4',
    asset: 'FRAX',
    price: '$1.002',
    change24h: '+0.15',
    isPositive: true,
    borrowApr: '4.95%',
    availableLiquidity: '$1.1M',
    logo: '🏛️'
  }
];

export function CDPSection() {
  const [selectedCDP, setSelectedCDP] = useState('CDP-001');

  const currentCDP = cdpPositions.find(cdp => cdp.id === selectedCDP);

  const getHealthColor = (ratio: number) => {
    if (ratio >= 2.0) return 'text-green-600';
    if (ratio >= 1.5) return 'text-yellow-600';
    return 'text-red-600';
  };

  const getStatusBadge = (status: string) => {
    switch (status) {
      case 'healthy':
        return <Badge className="bg-green-100 text-green-800 border-green-200">Healthy</Badge>;
      case 'warning':
        return <Badge className="bg-yellow-100 text-yellow-800 border-yellow-200">Warning</Badge>;
      case 'critical':
        return <Badge className="bg-red-100 text-red-800 border-red-200">Critical</Badge>;
      default:
        return <Badge variant="outline">Unknown</Badge>;
    }
  };

  if (!currentCDP) {
    return <div>CDP not found</div>;
  }

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-2xl font-semibold">CDP Management</h2>
          <p className="text-muted-foreground">Manage your collateralized debt positions</p>
        </div>
        <Button>
          <Plus className="h-4 w-4 mr-2" />
          Create New CDP
        </Button>
      </div>

      {/* CDP Selector */}
      <Card>
        <CardHeader>
          <CardTitle>Your CDPs</CardTitle>
        </CardHeader>
        <CardContent>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            {cdpPositions.map((cdp) => (
              <div
                key={cdp.id}
                className={`p-4 border rounded-lg cursor-pointer transition-all hover:bg-accent/50 ${
                  selectedCDP === cdp.id ? 'border-primary bg-accent/30' : ''
                }`}
                onClick={() => setSelectedCDP(cdp.id)}
              >
                <div className="flex items-center justify-between mb-2">
                  <span className="font-medium">{cdp.id}</span>
                  {getStatusBadge(cdp.status)}
                </div>
                <div className="space-y-1 text-sm">
                  <div className="flex justify-between">
                    <span className="text-muted-foreground">Collateral:</span>
                    <span>{cdp.totalCollateral}</span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-muted-foreground">Debt:</span>
                    <span>{cdp.totalDebt}</span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-muted-foreground">Health:</span>
                    <span className={getHealthColor(cdp.healthRatio)}>
                      {cdp.healthRatio.toFixed(2)}
                    </span>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </CardContent>
      </Card>

      <div className="space-y-6">
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center justify-between">
                <span>{currentCDP.id} Overview</span>
                {getStatusBadge(currentCDP.status)}
              </CardTitle>
            </CardHeader>
            <CardContent>
              <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
                <div>
                  <div className="text-sm text-muted-foreground">Total Collateral</div>
                  <div className="text-xl font-semibold">{currentCDP.totalCollateral}</div>
                </div>
                <div>
                  <div className="text-sm text-muted-foreground">Total Debt</div>
                  <div className="text-xl font-semibold">{currentCDP.totalDebt}</div>
                </div>
                <div>
                  <div className="text-sm text-muted-foreground">Health Ratio</div>
                  <div className={`text-xl font-semibold ${getHealthColor(currentCDP.healthRatio)}`}>
                    {currentCDP.healthRatio.toFixed(2)}
                  </div>
                </div>
                <div>
                  <div className="text-sm text-muted-foreground">Liquidation Price</div>
                  <div className="text-xl font-semibold">{currentCDP.liquidationPrice}</div>
                </div>
              </div>

              <div className="mt-6">
                <div className="flex justify-between items-center mb-2">
                  <span className="text-sm text-muted-foreground">Health Ratio</span>
                  <span className="text-sm">
                    {currentCDP.healthRatio < 1.5 ? 'Risk of Liquidation' : 'Safe'}
                  </span>
                </div>
                <Progress 
                  value={Math.min(currentCDP.healthRatio * 25, 100)} 
                  className="h-3"
                />
                <div className="flex justify-between text-xs text-muted-foreground mt-1">
                  <span>1.0 (Liquidation)</span>
                  <span>2.0+ (Safe)</span>
                </div>
              </div>

              {currentCDP.healthRatio < 1.5 && (
                <Alert className="mt-4 border-yellow-200 bg-yellow-50">
                  <AlertTriangle className="h-4 w-4 text-yellow-600" />
                  <AlertDescription className="text-yellow-800">
                    Your CDP is at risk of liquidation. Consider adding more collateral or repaying debt.
                  </AlertDescription>
                </Alert>
              )}
            </CardContent>
          </Card>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center justify-between">
                  <span>Collaterals</span>
                  <Button size="sm">
                    <Plus className="h-3 w-3 mr-1" />
                    Add
                  </Button>
                </CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                {currentCDP.collaterals.map((collateral, index) => (
                  <div key={`${currentCDP.id}-collateral-${index}`} className="flex items-center justify-between p-4 border rounded-lg hover:bg-accent/50 transition-colors">
                    <div className="flex items-center space-x-4">
                      <span className="text-2xl">{collateral.logo}</span>
                      <div>
                        <div className="font-medium">{collateral.asset}</div>
                        <div className="text-sm text-muted-foreground flex items-center space-x-2">
                          <span>{collateral.price}</span>
                          <div className={`flex items-center ${collateral.isPositive ? 'text-green-600' : 'text-red-600'}`}>
                            {collateral.isPositive ? (
                              <TrendingUp className="h-3 w-3 mr-1" />
                            ) : (
                              <TrendingDown className="h-3 w-3 mr-1" />
                            )}
                            <span>{collateral.change24h}%</span>
                          </div>
                        </div>
                      </div>
                    </div>
                    <div className="flex items-center space-x-6">
                      <div className="text-right">
                        <div className="text-sm text-muted-foreground">Amount</div>
                        <div className="font-medium">{collateral.amount} {collateral.asset}</div>
                      </div>
                      <div className="text-right">
                        <div className="text-sm text-muted-foreground">Value</div>
                        <div className="font-medium">{collateral.value}</div>
                      </div>
                      <div className="flex space-x-2">
                        <Button size="sm" variant="outline">
                          <Plus className="h-3 w-3 mr-1" />
                          Add
                        </Button>
                        <Button size="sm" variant="outline">
                          <Minus className="h-3 w-3 mr-1" />
                          Remove
                        </Button>
                      </div>
                    </div>
                  </div>
                ))}
              </CardContent>
            </Card>

            <Card>
              <CardHeader>
                <CardTitle className="flex items-center justify-between">
                  <span>Borrowed Assets</span>
                  <Button size="sm">
                    <Plus className="h-3 w-3 mr-1" />
                    Borrow
                  </Button>
                </CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                {currentCDP.loans.map((loan, index) => (
                  <div key={`${currentCDP.id}-loan-${index}`} className="flex items-center justify-between p-4 border rounded-lg hover:bg-accent/50 transition-colors">
                    <div className="flex items-center space-x-4">
                      <span className="text-2xl">{loan.logo}</span>
                      <div>
                        <div className="font-medium">{loan.asset}</div>
                        <div className="text-sm text-muted-foreground flex items-center space-x-2">
                          <span>{loan.price}</span>
                          <div className={`flex items-center ${loan.isPositive ? 'text-green-600' : 'text-red-600'}`}>
                            {loan.isPositive ? (
                              <TrendingUp className="h-3 w-3 mr-1" />
                            ) : (
                              <TrendingDown className="h-3 w-3 mr-1" />
                            )}
                            <span>{loan.change24h}%</span>
                          </div>
                        </div>
                      </div>
                    </div>
                    <div className="flex items-center space-x-6">
                      <div className="text-right">
                        <div className="text-sm text-muted-foreground">Borrowed</div>
                        <div className="font-medium">{loan.borrowed} {loan.asset}</div>
                      </div>
                      <div className="text-right">
                        <div className="text-sm text-muted-foreground">APR</div>
                        <div className="font-medium text-orange-600">{loan.interestRate}%</div>
                      </div>
                      <div className="flex space-x-2">
                        <Button size="sm" variant="outline">
                          <Plus className="h-3 w-3 mr-1" />
                          Borrow
                        </Button>
                        <Button size="sm" variant="outline">
                          <Minus className="h-3 w-3 mr-1" />
                          Repay
                        </Button>
                      </div>
                    </div>
                  </div>
                ))}
              </CardContent>
            </Card>
          </div>

          {/* Available Assets */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            {/* Available Collaterals */}
            <Card>
              <CardHeader>
                <CardTitle>Available Collaterals</CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                {availableCollaterals.map((collateral) => (
                  <div key={collateral.id} className="flex items-center justify-between p-4 border rounded-lg hover:bg-accent/50 transition-colors">
                    <div className="flex items-center space-x-4">
                      <span className="text-2xl">{collateral.logo}</span>
                      <div>
                        <div className="font-medium">{collateral.asset}</div>
                        <div className="text-sm text-muted-foreground flex items-center space-x-2">
                          <span>{collateral.price}</span>
                          <div className={`flex items-center ${collateral.isPositive ? 'text-green-600' : 'text-red-600'}`}>
                            {collateral.isPositive ? (
                              <TrendingUp className="h-3 w-3 mr-1" />
                            ) : (
                              <TrendingDown className="h-3 w-3 mr-1" />
                            )}
                            <span>{collateral.change24h}%</span>
                          </div>
                        </div>
                      </div>
                    </div>
                    <div className="flex items-center space-x-6">
                      <div className="text-right">
                        <div className="text-sm text-muted-foreground">LTV</div>
                        <div className="font-medium">{collateral.ltv}</div>
                      </div>
                      <div className="text-right">
                        <div className="text-sm text-muted-foreground">Total Supplied</div>
                        <div className="font-medium">{collateral.totalSupplied}</div>
                      </div>
                      <Button size="sm">
                        <Plus className="h-3 w-3 mr-1" />
                        Supply
                      </Button>
                    </div>
                  </div>
                ))}
              </CardContent>
            </Card>

            {/* Available Loan Resources */}
            <Card>
              <CardHeader>
                <CardTitle>Available Loan Resources</CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                {availableLoanResources.map((loanResource) => (
                  <div key={loanResource.id} className="flex items-center justify-between p-4 border rounded-lg hover:bg-accent/50 transition-colors">
                    <div className="flex items-center space-x-4">
                      <span className="text-2xl">{loanResource.logo}</span>
                      <div>
                        <div className="font-medium">{loanResource.asset}</div>
                        <div className="text-sm text-muted-foreground flex items-center space-x-2">
                          <span>{loanResource.price}</span>
                          <div className={`flex items-center ${loanResource.isPositive ? 'text-green-600' : 'text-red-600'}`}>
                            {loanResource.isPositive ? (
                              <TrendingUp className="h-3 w-3 mr-1" />
                            ) : (
                              <TrendingDown className="h-3 w-3 mr-1" />
                            )}
                            <span>{loanResource.change24h}%</span>
                          </div>
                        </div>
                      </div>
                    </div>
                    <div className="flex items-center space-x-6">
                      <div className="text-right">
                        <div className="text-sm text-muted-foreground">Borrow APR</div>
                        <div className="font-medium text-orange-600">{loanResource.borrowApr}</div>
                      </div>
                      <div className="text-right">
                        <div className="text-sm text-muted-foreground">Available Liquidity</div>
                        <div className="font-medium">{loanResource.availableLiquidity}</div>
                      </div>
                      <Button size="sm" variant="outline">
                        <Plus className="h-3 w-3 mr-1" />
                        Borrow
                      </Button>
                    </div>
                  </div>
                ))}
              </CardContent>
            </Card>
          </div>
      </div>
    </div>
  );
}

// src/lib/components/CDPSection.svelte
<script lang="ts">
  import ListRow from '$lib/components/common/ListRow.svelte';
  import TokenCell from '$lib/components/common/TokenCell.svelte';
  import StatusBadge from '$lib/components/common/StatusBadge.svelte';
  import HealthIndicator from '$lib/components/common/HealthIndicator.svelte';
  import HealthPill from '$lib/components/common/HealthPill.svelte';
  import Tabs from '$lib/components/common/Tabs.svelte';
  import Tab from '$lib/components/common/Tab.svelte';
  import AmountDisplay from '$lib/components/common/AmountDisplay.svelte';

  type Collateral = {
    asset: string;
    amount: string;
    value: string;
    price: string;
    change24h: string | number;
    isPositive: boolean;
    logo: string;
    ltv?: string;
  };

  type Loan = {
    asset: string;
    borrowed: string;
    interestRate: string;
    price: string;
    change24h: string | number;
    isPositive: boolean;
    logo: string;
  };

  type CDP = {
    id: string;
    collaterals: Collateral[];
    loans: Loan[];
    healthRatio: number;
    totalCollateral: string;
    totalDebt: string;
    liquidationPrice: string;
    status: 'healthy' | 'warning' | 'error' | string;
  };

  type AvailableCollateral = {
    id: string;
    asset: string;
    price: string;
    change24h: string | number;
    isPositive: boolean;
    ltv: string;
    totalSupplied: string;
    logo: string;
  };

  type LoanResource = {
    id: string;
    asset: string;
    price: string;
    change24h: string | number;
    isPositive: boolean;
    borrowApr: string;
    availableLiquidity: string;
    logo: string;
  };

  const cdpPositions: CDP[] = [
    { id: 'CDP-001', collaterals: [ { asset: 'ETH', amount: '5.0', value: '$12,500', price: '$2,485.67', change24h: '+3.24', isPositive: true, logo: '⟠', ltv: '75%' }, { asset: 'WBTC', amount: '0.15', value: '$6,750', price: '$67,234.12', change24h: '-1.85', isPositive: false, logo: '₿', ltv: '70%' } ], loans: [ { asset: 'USDC', borrowed: '8,500', interestRate: '5.25', price: '$1.00', change24h: '+0.02', isPositive: true, logo: '💰' }, { asset: 'DAI', borrowed: '2,000', interestRate: '4.85', price: '$0.998', change24h: '-0.12', isPositive: false, logo: '🪙' } ], healthRatio: 2.1, totalCollateral: '$19,250', totalDebt: '$10,500', liquidationPrice: '$1,890', status: 'healthy' },
    { id: 'CDP-002', collaterals: [ { asset: 'LINK', amount: '1,200', value: '$18,000', price: '$15.00', change24h: '+2.15', isPositive: true, logo: '🔗', ltv: '65%' } ], loans: [
       { asset: 'USDT', borrowed: '12,000', interestRate: '6.15', price: '$1.001', change24h: '+0.08', isPositive: true, logo: '💵' },
       { asset: 'USDTW', borrowed: '12,000', interestRate: '6.15', price: '$1.001', change24h: '+0.08', isPositive: true, logo: '💵' },
       ], healthRatio: 1.45, totalCollateral: '$18,000', totalDebt: '$12,000', liquidationPrice: '$12.50', status: 'warning' },
    { id: 'CDP-003', collaterals: [ { asset: 'MATIC', amount: '15,000', value: '$13,500', price: '$0.90', change24h: '-4.25', isPositive: false, logo: '🔷', ltv: '60%' } ], loans: [ { asset: 'DAI', borrowed: '7,200', interestRate: '4.95', price: '$0.998', change24h: '-0.12', isPositive: false, logo: '🪙' } ], healthRatio: 1.85, totalCollateral: '$13,500', totalDebt: '$7,200', liquidationPrice: '$0.65', status: 'healthy' }
  ];

  const availableCollaterals: AvailableCollateral[] = [
    { id: 'col1', asset: 'ETH', price: '$2,485.67', change24h: '+3.24', isPositive: true, ltv: '75%', totalSupplied: '$45.2M', logo: '⟠' },
    { id: 'col2', asset: 'WBTC', price: '$67,234.12', change24h: '-1.85', isPositive: false, ltv: '70%', totalSupplied: '$28.7M', logo: '₿' },
    { id: 'col3', asset: 'LINK', price: '$15.00', change24h: '+2.15', isPositive: true, ltv: '65%', totalSupplied: '$12.3M', logo: '🔗' },
    { id: 'col4', asset: 'MATIC', price: '$0.90', change24h: '-4.25', isPositive: false, ltv: '60%', totalSupplied: '$8.9M', logo: '🔷' }
  ];

  const availableLoanResources: LoanResource[] = [
    { id: 'loan1', asset: 'USDC', price: '$1.00', change24h: '+0.02', isPositive: true, borrowApr: '5.25%', availableLiquidity: '$2.5M', logo: '💰' },
    { id: 'loan2', asset: 'USDT', price: '$1.001', change24h: '+0.08', isPositive: true, borrowApr: '6.15%', availableLiquidity: '$1.8M', logo: '💵' },
    { id: 'loan3', asset: 'DAI', price: '$0.998', change24h: '-0.12', isPositive: false, borrowApr: '4.85%', availableLiquidity: '$2.2M', logo: '🪙' },
    { id: 'loan4', asset: 'FRAX', price: '$1.002', change24h: '+0.15', isPositive: true, borrowApr: '4.95%', availableLiquidity: '$1.1M', logo: '🏛️' }
  ];

  let selectedCDP = $state<string>('CDP-001');
  const currentCDP = $derived(cdpPositions.find((c) => c.id === selectedCDP));

  // Collateral sub-tabs state
  let collatTab = $state<'normal' | 'ftw' | 'nftw'>('normal');

  // Example fungible wrapper positions (multi-underlying baskets)
  type FtWrapperPos = {
    id: string;
    wrapper: string; // wrapper token symbol/name
    shares: number;
    usd: number; // total valuation in USD
    underlyings: { logo: string; symbol: string }[];
  };

  const ftWrappersByCdp: Record<string, FtWrapperPos[]> = {
    'CDP-001': [
      { id: 'ftw-1', wrapper: 'lpUSDC-DAI', shares: 1250.23456789, usd: 1250.23, underlyings: [ { logo: '💰', symbol: 'USDC' }, { logo: '🪙', symbol: 'DAI' } ] }
    ],
    'CDP-002': [
      { id: 'ftw-2', wrapper: 'stETH', shares: 2.3456789, usd: 5825.67, underlyings: [ { logo: '⟠', symbol: 'ETH' } ] }
    ],
    'CDP-003': []
  };
  const ftWrappers = $derived(ftWrappersByCdp[selectedCDP] ?? []);

  // Example NFT wrapper positions
  type NftWrapperPos = {
    id: string;
    collection: string;
    count: number; // number of NFT ids in wrapper lot
    usd: number; // total valuation in USD
    icons: string[]; // small previews
  };

  const nftWrappersByCdp: Record<string, NftWrapperPos[]> = {
    'CDP-001': [ { id: 'nftw-1', collection: 'BlueChip Apes', count: 3, usd: 128_500, icons: ['🦍','🦍','🦍','🦍'] } ],
    'CDP-002': [ { id: 'nftw-2', collection: 'Art Blocks', count: 5, usd: 54_200, icons: ['🎨','🧩','🖼️','🖌️','🖼️'] } ],
    'CDP-003': []
  };
  const nftWrappers = $derived(nftWrappersByCdp[selectedCDP] ?? []);

  // Health and status handled by imported components
  function parseUsdStr(s: string): number {
    return Number.parseFloat(s.replace(/[$,\s]/g, '')) || 0;
  }
  function parseUnitsStr(s: string): number {
    return Number.parseFloat(s.replace(/[,\s]/g, '')) || 0;
  }
</script>

<div class="space-y-6">
  <div class="flex items-center justify-between">
    <div>
      <h2 class="text-2xl font-semibold">CDP Management</h2>
      <p class="opacity-70">Manage your collateralized debt positions</p>
    </div>
    <button class="btn btn-primary">
      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" class="h-4 w-4 mr-2"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4v16m8-8H4"/></svg>
      Create New CDP
    </button>
  </div>

  <!-- CDP Selector -->
  <div class="card bg-base-200">
    <div class="card-body py-3">
      <div class="flex items-center gap-3">
        <h2 class="card-title shrink-0 m-0">Your CDPs</h2>
        <div class="flex-1 overflow-x-auto">
          <div class="flex items-center justify-end gap-2 w-max ml-auto">
            {#each cdpPositions as cdp}
              <button
                class={
                  "btn btn-sm " + (selectedCDP === cdp.id ? "btn-active btn-outline" : "btn-ghost")
                }
                onclick={() => (selectedCDP = cdp.id)}
              >
                <span class="font-medium">{cdp.id}</span>
                <span class="ml-2"><HealthPill ratio={cdp.healthRatio} /></span>
              </button>
            {/each}
          </div>
        </div>
      </div>
    </div>
  </div>

  {#if currentCDP}
    <div class="space-y-6">
      <div class="card card-compact bg-base-200">
        <div class="card-body py-3">
          <div class="flex items-center justify-between">
            <h2 class="card-title text-base">{currentCDP.id} Overview</h2>
            <!-- <StatusBadge status={currentCDP.status} /> -->
          </div>

          <div class="grid grid-cols-2 md:grid-cols-4 gap-3 mt-2">
            <div>
              <div class="text-sm opacity-70">Total Collateral</div>
              <div class="text-lg font-semibold">{currentCDP.totalCollateral}</div>
            </div>
            <div>
              <div class="text-sm opacity-70">Total Debt</div>
              <div class="text-lg font-semibold">{currentCDP.totalDebt}</div>
            </div>
                 <div>
              <div class="text-sm opacity-70">Liquidation Price</div>
              <div class="text-lg font-semibold">{currentCDP.liquidationPrice}</div>
            </div>  
            <div>
              <div class="text-sm opacity-70">Health</div>
              <div class="text-lg font-semibold"><HealthPill ratio={currentCDP.healthRatio} showValue={true} /></div>
            </div>
  
          </div>

          <!-- <div class="mt-3">
            <div class="flex justify-between items-center mb-1">
              <span class="text-xs opacity-70">Health Ratio</span>
              <span class="text-xs">{currentCDP.healthRatio < 1.5 ? 'Risk of Liquidation' : 'Safe'}</span>
            </div>
            <progress class="progress progress-primary h-2" max="100" value={Math.min(currentCDP.healthRatio * 25, 100)}></progress>
            <div class="flex justify-between text-[10px] opacity-70 mt-1">
              <span>1.0 (Liquidation)</span>
              <span>2.0+ (Safe)</span>
            </div>
          </div> -->

          {#if currentCDP.healthRatio < 1.5}
            <div role="alert" class="alert alert-warning mt-3 text-xs">
              <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 9v2m0 4h.01M4.93 19h14.14c1.54 0 2.5-1.67 1.73-3L13.73 4c-.77-1.33-2.69-1.33-3.46 0L3.2 16c-.77 1.33.19 3 1.73 3z"/></svg>
              <span>Your CDP is at risk of liquidation. Consider adding more collateral or repaying debt.</span>
            </div>
          {/if}
        </div>
      </div>

      <div class="space-y-6">
        <div class="card bg-base-200">
          <div class="card-body">
            <div class="flex items-center justify-between">
              <h3 class="card-title">Collaterals</h3>
              <button class="btn btn-sm btn-outline">Add</button>
            </div>

            <div class="mt-2">
              <Tabs>
                <Tab id="normal" bind:activeId={collatTab} label="Normal" />
                <Tab id="ftw" bind:activeId={collatTab} label="Fungible Wrappers" />
                <Tab id="nftw" bind:activeId={collatTab} label="NFT Wrappers" />
              </Tabs>
            </div>

            {#if collatTab === 'normal'}
              <div class="mt-3 space-y-3">
                {#each currentCDP.collaterals as collateral, index}
                  <ListRow>
                    {#snippet left()}
                      <TokenCell logo={collateral.logo} symbol={collateral.asset} price={collateral.price} change={collateral.change24h} isPositive={collateral.isPositive} />
                    {/snippet}
                    {#snippet right()}
                      <div class="flex items-center gap-6">
                        <div class="text-right">
                          <AmountDisplay amount={parseUnitsStr(collateral.amount)} symbol={collateral.asset} usd={parseUsdStr(collateral.value)} />
                        </div>
                        <div class="text-right">
                          <div class="text-sm opacity-70">LTV</div>
                          <div class="font-medium">{collateral.ltv ?? '-'}</div>
                        </div>
                        <div class="flex gap-2">
                          <button class="btn btn-sm btn-outline">Add</button>
                          <button class="btn btn-sm btn-outline">Remove</button>
                        </div>
                      </div>
                    {/snippet}
                  </ListRow>
                {/each}
              </div>
            {:else if collatTab === 'ftw'}
              <div class="mt-3 space-y-3">
                {#each ftWrappers as w}
                  <ListRow>
                    {#snippet left()}
                      <div class="flex items-center gap-3">
                        <div class="font-medium">{w.wrapper}</div>
                        <div class="badge badge-outline badge-xs">Wrapper</div>
                        <div class="flex -space-x-2">
                          {#each w.underlyings.slice(0, 4) as u}
                            <div class="avatar placeholder">
                              <div class="bg-base-200 w-6 h-6 rounded-full ring ring-base-100 ring-offset-1 text-[10px] flex items-center justify-center">{u.logo}</div>
                            </div>
                          {/each}
                          {#if w.underlyings.length > 4}
                            <div class="avatar placeholder">
                              <div class="bg-base-300 w-6 h-6 rounded-full ring ring-base-100 ring-offset-1 text-[10px] flex items-center justify-center">+{w.underlyings.length - 4}</div>
                            </div>
                          {/if}
                        </div>
                      </div>
                    {/snippet}
                    {#snippet right()}
                      <div class="flex items-center gap-6">
                        <div class="text-right">
                          <AmountDisplay amount={w.shares} symbol={w.wrapper} usd={w.usd} />
                        </div>
                        <div class="flex gap-2">
                          <button class="btn btn-sm btn-outline">Add</button>
                          <button class="btn btn-sm btn-outline">Remove</button>
                          <button class="btn btn-sm btn-outline">Unwrap</button>
                        </div>
                      </div>
                    {/snippet}
                  </ListRow>
                {/each}
              </div>
            {:else}
              <div class="mt-3 space-y-3">
                {#each nftWrappers as n}
                  <ListRow>
                    {#snippet left()}
                      <div class="flex items-center gap-3">
                        <div class="font-medium">{n.collection}</div>
                        <div class="badge badge-outline badge-xs">NFT Wrapper</div>
                        <div class="flex -space-x-2">
                          {#each n.icons.slice(0, 4) as ic}
                            <div class="avatar placeholder">
                              <div class="bg-base-200 w-6 h-6 rounded-full ring ring-base-100 ring-offset-1 text-[10px] flex items-center justify-center">{ic}</div>
                            </div>
                          {/each}
                          {#if n.icons.length > 4}
                            <div class="avatar placeholder">
                              <div class="bg-base-300 w-6 h-6 rounded-full ring ring-base-100 ring-offset-1 text-[10px] flex items-center justify-center">+{n.icons.length - 4}</div>
                            </div>
                          {/if}
                        </div>
                      </div>
                    {/snippet}
                    {#snippet right()}
                      <div class="flex items-center gap-6">
                        <div class="text-right">
                          <AmountDisplay amount={n.count} symbol={'NFTs'} usd={n.usd} />
                        </div>
                        <div class="flex gap-2">
                          <button class="btn btn-sm btn-outline">Add</button>
                          <button class="btn btn-sm btn-outline">Remove</button>
                          <button class="btn btn-sm btn-outline">Unwrap</button>
                        </div>
                      </div>
                    {/snippet}
                  </ListRow>
                {/each}
              </div>
            {/if}
          </div>
        </div>

        <div class="card card-compact bg-base-200">
          <div class="card-body py-3">
            <div class="flex items-center justify-between">
              <h3 class="card-title">Borrowed Assets</h3>
              <button class="btn btn-sm btn-outline">Borrow</button>
            </div>

            <div class="mt-3 space-y-3">
              {#each currentCDP.loans as loan, index}
                <ListRow>
                  {#snippet left()}
                    <TokenCell logo={loan.logo} symbol={loan.asset} price={loan.price} change={loan.change24h} isPositive={loan.isPositive} />
                  {/snippet}
                  {#snippet right()}
                    <div class="flex items-center gap-6">
                      <div class="text-right">
                        <AmountDisplay amount={parseUnitsStr(loan.borrowed)} symbol={loan.asset} usd={parseUsdStr(loan.price) * parseUnitsStr(loan.borrowed)} />
                      </div>
                      <div class="text-right">
                        <div class="text-sm opacity-70">Interest</div>
                        <div class="font-medium text-warning">{loan.interestRate}</div>
                      </div>
                    <div class="flex gap-2">
                      <button class="btn btn-sm btn-outline">Repay</button>
                      <button class="btn btn-sm btn-outline">Borrow</button>
                    </div>
                    </div>
                  {/snippet}
                </ListRow>
              {/each}
            </div>
          </div>
        </div>
      </div>

      <!-- Available Assets -->
      <!-- <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
        <div class="card bg-base-200">
          <div class="card-body">
            <h3 class="card-title">Available Loan Resources</h3>
            <div class="mt-3 space-y-3">
              {#each availableLoanResources as loanResource}
                <ListRow>
                  {#snippet left()}
                    <TokenCell logo={loanResource.logo} symbol={loanResource.asset} price={loanResource.price} change={loanResource.change24h} isPositive={loanResource.isPositive} />
                  {/snippet}
                  {#snippet right()}
                    <div class="flex items-center gap-6">
                      <div class="text-right">
                        <div class="text-sm opacity-70">Borrow APR</div>
                        <div class="font-medium text-warning">{loanResource.borrowApr}</div>
                      </div>
                      <div class="text-right">
                        <div class="text-sm opacity-70">Available Liquidity</div>
                        <div class="font-medium">{loanResource.availableLiquidity}</div>
                      </div>
                    <button class="btn btn-sm btn-outline">Borrow</button>
                    </div>
                  {/snippet}
                </ListRow>
              {/each}
            </div>
          </div>
        </div>
      </div> -->
    </div>
  {:else}
    <div class="text-error">CDP not found</div>
  {/if}
</div>
